# Tomcat Server
server:
  port: 8080

# Logger
logging.level:
  web: DEBUG
  '[com.busyqa.coop]': DEBUG
  '[org.hibernate.type]': INFO
  
# Active Profile
spring:
  profiles:
    active: default
    
# Banner Text
  banner:
    charset: UTF-8
    location: classpath:/banner/busyQA.txt

# Jackson Settings
  jackson:
    date-format: "yyyy-MM-dd"  
    
# Secret-Key    
jwt:
  secret: "secret"

---

# Default Profile
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdatabase?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC 
    username: root
    password: Clicketyclack123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 15
      max-idle: 10
      initial-size: 3
      test-on-borrow: true
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: update
        '[format_sql]': true
        use-new-id-generator-mappings: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  sql:
    init:
      continue-on-error: false
  config:
    activate:
      on-profile: default
      
 
      
      # Database Settings

---

# Prod Profile
server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://busyqa-rds.javadev.ca:3306/usersdb?autoReconnect=true&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: busyqa
    password: busyqa123$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: update
        '[format_sql]': true
        use-new-id-generator-mappings: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy 
  sql:
    init:
      continue-on-error: false
  config:
    activate:
      on-profile: prod
      
      # Database Settings

