INSERT ROLE(NAME_ROLE,DESC_ROLE,STATUS)
VALUES('Admin','Admin','A');
INSERT ROLE(NAME_ROLE,DESC_ROLE,STATUS)
VALUES('Manager','Manager','A');
INSERT ROLE(NAME_ROLE,DESC_ROLE,STATUS)
VALUES('Simple_User','Simple_User','A');